AdventureWorks2/Models/ErrorHandler.cs
namespace AdventureWorks2.Models
{
    public class ErrorHandler
    {
        public string? Title { get; set; }
        public string? ErrorMessage { get; set; }
        public string? Path { get; set; }
    }
}

AdventureWorks2/Models/UserAccess.cs
namespace AdventureWorks2.Models
{
    public class UserAccess
    {
        public string? BusinessEntityID { get; set; }
        public string? Controller { get; set; }
        public string? Action { get; set; }
        public string? DatabaseAction { get; set; }
    }
}

AdventureWorks2/Controllers/EmailController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Net.Mail;
using System.Net;
using System.Reflection;
using AdventureWorks2.Models;
using System.IO;
using System.Globalization;

namespace AdventureWorks2.Controllers
{
    public class EmailController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(EmailModel model)
        {
            /*claseprogra5castrocarazo@gmail.com*/
            /*Admin$1234*/
            /*vxttcmdwibjyeeoy*/

            using (MailMessage mm = new MailMessage(model.Email, model.To))
            {
                mm.Subject = model.Subject;
                /*mm.Body = model.Body;*/
                /*if (model.Attachment.Length > 0)
                {
                    using (var stream = model.Attachment.OpenReadStream())
                    {
                        var attachment = new Attachment(stream, model.Attachment.FileName);
                        mm.Attachments.Add(attachment);
                    }
                }*/
                mm.IsBodyHtml = true;

                /**/
                using (var sr = new StreamReader("wwwroot/html/welcome.txt"))
                {
                    // Read the stream as a string, and write the string to the console.
                    string body =  sr.ReadToEnd().Replace("@CLIENTNAME", "SAMUEL");

                    mm.Body = body;
                }
                /**/


                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.EnableSsl = true;
                NetworkCredential NetworkCred = new NetworkCredential(model.Email, model.Password);
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = NetworkCred;
                smtp.Port = 587;
                smtp.Send(mm);
                ViewBag.Message = "Email sent.";
            }

            return View();
        }

        // GET: EmailController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: EmailController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EmailController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EmailController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: EmailController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EmailController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: EmailController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AdventureWorks2/Controllers/ProductsController.cs
using AdventureWorks.DatabaseHelper;
using AdventureWorks2.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;

namespace AdventureWorks2.Controllers
{
    public class ProductsController : Controller
    {
        // GET: ProductsController
        public ActionResult Index()
        {
            ViewBag.CategoriesList = GetCatalog("spGetProductCategories", null);            

            return View();
        }

        public ActionResult LoadSubCategories(int categoryId)
        {
            ViewBag.CategoriesList = GetCatalog("spGetProductCategories", null);
            ViewBag.SubCategoriesList = GetCatalog("spGetSubProductCategory", new List<SqlParameter> { new SqlParameter("@ProductCategoryID", categoryId) });

            return View("Index");
        }

        public ActionResult LoadProducts(int subCategoryId)
        {
            ViewBag.CategoriesList = GetCatalog("spGetProductCategories", null);            

            List<Product> products = new List<Product>();
            foreach (DataRow item in DatabaseHelper.ExecuteStoreProcedure("spGetProducts", new List<SqlParameter> { new SqlParameter("@ProductSubcategoryID", subCategoryId) }).Rows)
            {
                products.Add(new Product
                {
                    Name = item["Name"].ToString(),
                    Color = item["Color"].ToString(),
                    ProductNumber = item["ProductNumber"].ToString(),
                    ListPrice = Convert.ToDecimal(item["ListPrice"]),
                });
            }

            ViewBag.ProductsList = products;

            return View("Index");
        }

        public List<Catalog> GetCatalog(string storeProcedure, List<SqlParameter>? list)
        {
            List<Catalog> catalogList = new List<Catalog>();
            foreach (DataRow item in DatabaseHelper.ExecuteStoreProcedure(storeProcedure, list).Rows)
            {
                catalogList.Add(new Catalog
                {
                    Id = Convert.ToUInt16(item["id"]),
                    Desc = item["desc"].ToString()
                });
            }

            return catalogList;
        }
    }
}

AdventureWorks2/Views/Shared/ErrorHandler.cshtml
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">@ViewBag.Error.Title</h1>
<h2 class="text-danger">@ViewBag.Error.ErrorMessage</h2>
<a href="@ViewBag.Error.Path">Try again?</a> 

AdventureWorks2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - AdventureWorks2</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/AdventureWorks2.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
	<script src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AdventureWorks2</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li id="HomeIndex" class="nav-item" hidden="hidden">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li id="HomePrivacy" class="nav-item" hidden="hidden">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
						<li id="ProductsIndex" class="nav-item" hidden="hidden">
							<a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
						</li>
						<li id="ProductsIndex" class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Email" asp-action="Index">Send Email</a>
						</li>
						<li id="EmployeesIndex" class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employes</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2022 - AdventureWorks2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AdventureWorks2/Views/Shared/userAccess.cshtml
<script type="text/javascript">
	var api = new XMLHttpRequest();
	api.open("GET", "/Login/GetCurrentSessionUserAccess");
	api.send();

	api.onreadystatechange = function () {
		if (this.readyState == 4 && this.status == 200) {

			let data = JSON.parse(this.responseText);

			data.forEach((item) => {
				document.getElementById(item.controller + item.action).removeAttribute("hidden");
			});
		}
	};
</script>